version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm run start:test
          wait-on: http://localhost:8080
          post-steps:
            - run: npm run check:coverage
